version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    expose:
      - PORTAINER_PORT1
      - PORTAINER_PORT2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$DOMAIN_NAME`)" 
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=$PORTAINER_PORT2"
      - "traefik.http.routers.portainer.tls.certresolver=homelab"
    networks:
      - monitoring

  traefik:
    container_name: reverse_proxy
    image: traefik:latest
    command: 
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--metrics.prometheus=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.homelab.acme.tlschallenge=true"
      - "--certificatesresolvers.homelab.acme.email=matthieurobert82@gmail.com"
      - "--certificatesresolvers.homelab.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.routers.api.rule=Host (`traefik.$DOMAIN_NAME`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=$TRAEFIK_AUTH_USER"
      - "traefik.http.routers.api.tls.certresolver=homelab"
    ports:
      - "$TRAEFIK_PORT1:$TRAEFIK_PORT1"
      - "$TRAEFIK_PORT2:$TRAEFIK_PORT2"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # devices:
    #   - /dev/kmsg
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.$DOMAIN_NAME`)" 
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "traefik.http.routers.cadvisor.tls.certresolver=homelab"
    networks:
      - monitoring

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    expose:
      - 9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.$DOMAIN_NAME`)" 
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=$TRAEFIK_AUTH_USER"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.tls.certresolver=homelab"  
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAIN_NAME`)" 
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls.certresolver=homelab"
    networks:
      - monitoring

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    expose:
      - 8123
    # network_mode: host
    networks:
      - monitoring
      # - homeassistant
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.$DOMAIN_NAME`)" 
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.tls.certresolver=homelab"
    devices:
      - /dev/serial/by-id:/dev/serial/by-id

volumes:
  postgres-data:
  portainer_data:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
  homeassistant:
    driver: host
