---
all:
  vars:
    email: matthieurobert82@gmail.com
    ansible_user: debian
  children:
    single:
      hosts:
        ovh-vps:
  hosts:
    ovh-vps:
      ansible_host: 162.19.27.12
      project: k0s-ovh
      domain_name: dev.mrobert.fr
