apiVersion: v1
kind: Namespace
metadata:
  name: docker
---
kind: Service
apiVersion: v1
metadata:
  name: external-minio
spec:
  ports:
  - protocol: TCP
    port: 9001
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-minio
subsets:
- addresses:
  - ip: 192.168.1.44
  ports:
  - port: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-minio
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - minio.kube.homelab.mrobert.fr
    secretName: minio.kube.homelab.mrobert.fr-tls
  rules:
  - host: minio.kube.homelab.mrobert.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-minio
            port: 
              number: 9001